# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
