# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_dojos_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninjas',
            name='dojos',
        ),
        migrations.RenameField(
            model_name='dojos',
            old_name='city',
            new_name='confirm_password',
        ),
        migrations.RenameField(
            model_name='dojos',
            old_name='name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='dojos',
            old_name='state',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='dojos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojos',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojos',
            name='password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dojos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ninjas',
        ),
    ]
