# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='desc',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
