# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0006_item_desc'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('itemManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='users',
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dojo_ninjas.User'),
            preserve_default=False,
        ),
    ]
